### ISSUE TITLE
error messages should contain the error context

### ISSUE THREAD

**Issue by lestrrat** [builderscon/conf.builderscon.io#8]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

多分これはAPIサーバーにアクセスできていないのだけど、コンテキストがないので全くデバッグが進まない。「どのURLにアクセスを試みようとしたのか」等のコンテキスト情報を付与してからトレースを発生させるようにしてください。

**Comment by lestrrat** [comment]
ああ、やっと`HTTPConnectionPool(host='api.dev.builderscon.io', port=80)` を見つけた。ともあれ、こうではなく、エラーはまず

* 「○○という作業をしようとしていて」
* 「○○というリソースにアクセスしようとしたら」
* 「○○というエラーが出た」

みたいな、大枠の処理の名称、具体的になにをしようとしていたところだったか、そしてエラーの中身、というのがまず真っ先にでるようにして、それ以外の不必要なトレースはなるたけ発生させないでください
